nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.aa ../data-lfs/journals-output >logs/alignlog.aa &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.au ../data-lfs/journals-output >logs/alignlog.au &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.ab ../data-lfs/journals-output >logs/alignlog.ab &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.av ../data-lfs/journals-output >logs/alignlog.av &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.ac ../data-lfs/journals-output >logs/alignlog.ac &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.aw ../data-lfs/journals-output >logs/alignlog.aw &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.ad ../data-lfs/journals-output >logs/alignlog.ad &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.ax ../data-lfs/journals-output >logs/alignlog.ax &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.ae ../data-lfs/journals-output >logs/alignlog.ae &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.ay ../data-lfs/journals-output >logs/alignlog.ay &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.af ../data-lfs/journals-output >logs/alignlog.af &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.az ../data-lfs/journals-output >logs/alignlog.az &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.ag ../data-lfs/journals-output >logs/alignlog.ag &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.ba ../data-lfs/journals-output >logs/alignlog.ba &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.ah ../data-lfs/journals-output >logs/alignlog.ah &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.bb ../data-lfs/journals-output >logs/alignlog.bb &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.ai ../data-lfs/journals-output >logs/alignlog.ai &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.bc ../data-lfs/journals-output >logs/alignlog.bc &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.aj ../data-lfs/journals-output >logs/alignlog.aj &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.bd ../data-lfs/journals-output >logs/alignlog.bd &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.ak ../data-lfs/journals-output >logs/alignlog.ak &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.be ../data-lfs/journals-output >logs/alignlog.be &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.al ../data-lfs/journals-output >logs/alignlog.al &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.bf ../data-lfs/journals-output >logs/alignlog.bf &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.am ../data-lfs/journals-output >logs/alignlog.am &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.bg ../data-lfs/journals-output >logs/alignlog.bg &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.an ../data-lfs/journals-output >logs/alignlog.an &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.bh ../data-lfs/journals-output >logs/alignlog.bh &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.ao ../data-lfs/journals-output >logs/alignlog.ao &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.bi ../data-lfs/journals-output >logs/alignlog.bi &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.ap ../data-lfs/journals-output >logs/alignlog.ap &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.bj ../data-lfs/journals-output >logs/alignlog.bj &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.aq ../data-lfs/journals-output >logs/alignlog.aq &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.bk ../data-lfs/journals-output >logs/alignlog.bk &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.ar ../data-lfs/journals-output >logs/alignlog.ar &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.bl ../data-lfs/journals-output >logs/alignlog.bl &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.as ../data-lfs/journals-output >logs/alignlog.as &
nohup python AlignJournals.py ../data-lfs/html-labels-accurate/ground-truth-url.part.at ../data-lfs/journals-output >logs/alignlog.at &

