nohup python AlignJournals.py ground-url-seg/ground-truth-url.aa ../data-lfs/journals-output >logs/alignlog.aa &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.ai ../data-lfs/journals-output >logs/alignlog.ai &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.aq ../data-lfs/journals-output >logs/alignlog.aq &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.ay ../data-lfs/journals-output >logs/alignlog.ay &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.bg ../data-lfs/journals-output >logs/alignlog.bg &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.ab ../data-lfs/journals-output >logs/alignlog.ab &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.aj ../data-lfs/journals-output >logs/alignlog.aj &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.ar ../data-lfs/journals-output >logs/alignlog.ar &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.az ../data-lfs/journals-output >logs/alignlog.az &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.bh ../data-lfs/journals-output >logs/alignlog.bh &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.ac ../data-lfs/journals-output >logs/alignlog.ac &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.ak ../data-lfs/journals-output >logs/alignlog.ak &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.as ../data-lfs/journals-output >logs/alignlog.as &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.ba ../data-lfs/journals-output >logs/alignlog.ba &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.bi ../data-lfs/journals-output >logs/alignlog.bi &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.ad ../data-lfs/journals-output >logs/alignlog.ad &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.al ../data-lfs/journals-output >logs/alignlog.al &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.at ../data-lfs/journals-output >logs/alignlog.at &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.bb ../data-lfs/journals-output >logs/alignlog.bb &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.bj ../data-lfs/journals-output >logs/alignlog.bj &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.ae ../data-lfs/journals-output >logs/alignlog.ae &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.am ../data-lfs/journals-output >logs/alignlog.am &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.au ../data-lfs/journals-output >logs/alignlog.au &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.bc ../data-lfs/journals-output >logs/alignlog.bc &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.bk ../data-lfs/journals-output >logs/alignlog.bk &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.af ../data-lfs/journals-output >logs/alignlog.af &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.an ../data-lfs/journals-output >logs/alignlog.an &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.av ../data-lfs/journals-output >logs/alignlog.av &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.bd ../data-lfs/journals-output >logs/alignlog.bd &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.bl ../data-lfs/journals-output >logs/alignlog.bl &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.ag ../data-lfs/journals-output >logs/alignlog.ag &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.ao ../data-lfs/journals-output >logs/alignlog.ao &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.aw ../data-lfs/journals-output >logs/alignlog.aw &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.be ../data-lfs/journals-output >logs/alignlog.be &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.ah ../data-lfs/journals-output >logs/alignlog.ah &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.ap ../data-lfs/journals-output >logs/alignlog.ap &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.ax ../data-lfs/journals-output >logs/alignlog.ax &
nohup python AlignJournals.py ground-url-seg/ground-truth-url.bf ../data-lfs/journals-output >logs/alignlog.bf &
